### ISSUE TITLE
Incorrect error message about board file.

### ISSUE THREAD

**Issue by dangitall** [jonm/SillyMUD#36]
Seeing `Board-message file corrupt, nonexistent, or empty.` in log but it seems to be restoring the board.

**Comment by dangitall** [comment]
Not an issue, these messages were about other boards that actually didn't exist yet.

**Comment by jonm** [comment]
Actually, this may be an issue; I recently fixed it so it will create an
empty messages file if one doesn't exist. However, I do think the log
message here needs to be updated; an empty board file should issue a
"warning" (maybe?) but a corrupt file should issue an "error". And really
the code ought to distinguish those two cases.

**Comment by dangitall** [comment]
Ok. PR submitted.
