### ISSUE TITLE
permit logging to file instead of stdout/stderr

### ISSUE THREAD

**Issue by jonm** [jonm/SillyMUD#54]
It'd be nice to be able to direct output to `/usr/local/var/log/sillymud/XXXX` so we can look at things there instead of `nohup.out` which is how I'm running the prod instance currently. I suspect there is probably a good C logging library/best practice that could be used here.

**Comment by dangitall** [comment]
Yeah, good idea. The most immediate solution that comes to mind is to use `openlog`/`syslog`  and then a rule in syslogd.conf to route silly messages to a specific file.
