### ISSUE TITLE
shops do not seem to work anymore

### ISSUE THREAD

**Issue by jonm** [jonm/SillyMUD#72]
Can't `list` or `value` in shops in Midgaard anymore. You get:

`Sorry, but you cannot do that here!`

**Comment by dangitall** [comment]
Ack! Sounds like I broke something. Sorry, I'm on the road and won't be able to look at this until Saturday.

**Comment by jonm** [comment]
It's not a problem. I am poking around on it. I don't have any money to spend anyway. :)

**Comment by jonm** [comment]
Ok, here's some info I've found so far. If I go to the general store in Midgaard, and I do `stat room`, the room does not have a special proc; if I `stat grocer` it does seem to have a special proc. However, it doesn't seem to be firing, or at least the `special()` command in `interpreter.c` is returning `0`. Possibly the shopkeeper function isn't returning `1` when it should? Haven't investigated it further yet, and am going to take a break for a bit.

**Comment by jonm** [comment]
Hmm, further investigation shows this does in fact work when running the latest master code at 70ca09da6528cfe18d406b866d5115be6dd1504d locally. Perhaps this got broken and then restored at some point. I will try deploying the latest code to prod.

**Comment by jonm** [comment]
Ugh, I have botched production somehow and can't figure out what I did. All the data files seem to match what are in the repo, but for some reason the previous version (0.1.3) won't boot and the latest version (0.1.5) has zone loading errors. I have a copy of the player file saved in the `ec2-user` home directory.

**Comment by jonm** [comment]
Ok, now the issue seems to be the mob and object indices; seems like the zone files can't resolve references to mob or object virtual numbers.

**Comment by jonm** [comment]
Ok, I have the latest version installed in prod, and you can see the zone loading errors in the production log.

**Comment by jonm** [comment]
Also found out: if you remove `/usr/local/var/sillymud/silly.log` in production you have to restart `rsyslogd` to get the log to show up again.

**Comment by jonm** [comment]
Ok, #76 seemed to correct this. Zone loading now working in production, and shops working again.
