### ISSUE TITLE
rotate production log

### ISSUE THREAD

**Issue by jonm** [jonm/SillyMUD#75]
The game currently logs to `syslog` when running in daemon mode; we should figure out a configuration for `rsyslogd` that allows for periodic rotation/truncation of logs (and then document that in the `INSTALL` doc).

**Comment by dangitall** [comment]
IIRC you can do some `rsyslogd` configuration to do log rotation but I would personally just add an entry on your server for the `logrotate` cronjob to run. Do you have a strong preference here?

**Comment by jonm** [comment]
I guess my preference would be to figure out how to get `rsyslogd` to do the rotation, although I agree it's probably quicker to just do `logrotate` with an `/etc/init.d/rsyslogd restart` or `kill -HUP` afterwards.

**Comment by dangitall** [comment]
I looked into doing this with `rsyslogd` and have decided that this is not my definition of fun. I added a `logrotate` config entry on the ec2 instance. If you really want this done differently we can negotiate later. :smile:

**Comment by jonm** [comment]
No, this is fine. Big fan of pragmatism. :)
