### ISSUE TITLE
release numbering / semantic versioning discussion

### ISSUE THREAD

**Issue by jonm** [jonm/SillyMUD#79]
Proposal: use [semantic versioning](http://semver.org/) for release numbers.

`<major>.<minor>.<patch>`

Currently we are at `0.1.10`. I would characterize our progress thus far as we've made things runnable but probably not cleaned up enough to warrant a `1.0.0`. As a `0.x.y` version, we should get some leeway on backwards compatibility. So I propose, for now:
- Refactoring and bug fixes should increment the _patch_ number
- Introduction of new features should increment the _minor_ number (e.g. adding ability to log to syslog)
- Changes that change the format of data files, whether shipped with the game, or created by the game, should increment _minor_ until we decide we are at `1.0.0`; thereafter those are probably _major_ releases unless we can do them in a backwards-compatible fashion

**Comment by dangitall** [comment]
:+1:

**Comment by jonm** [comment]
Ok, captured in a [wiki doc](https://github.com/jonm/SillyMUD/wiki/Releases) with a reference back here.
